# Site settings
title: Soapbox Systems
email: nick@soapbox.systems
description: > # this means to ignore newlines until "url:"
    The truth never damages a cause that is just. 
url: "https://soapbox.systems" 
twitter_username: boxsoapbot
github_username:  soapboxsys
navigation: 
    - text: bip-100
    - url: /bip-100/


# Build settings
markdown: kramdown
