# Site settings
title: Soapbox Systems
email: nskelsey@gmail.com
description: > # this means to ignore newlines until "url:"
    The truth never damages a cause that is just. 
url: "https://soapbox.systems" 
twitter_username: boxsoapbot
github_username:  soapboxsys

# Build settings
markdown: kramdown
